### ISSUE TITLE
有后端项目吗

### ISSUE THREAD

**Issue by kirbystudy** [zqqqqz2000/intelligent-construction-front#1]

**Comment by zqqqqz2000** [comment]
有的。甚至还有安卓的
[https://github.com/zqqqqz2000/intelligent-construction-android](url)
[https://github.com/zqqqqz2000/intelligent-construction-server](url)

**Comment by kirbystudy** [comment]
谢了哈老哥，但是后端我用java的 对python不太熟悉




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zqqqqz2000/intelligent-construction-front"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月22日(星期二) 晚上10:04
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zqqqqz2000/intelligent-construction-front] 有后端项目吗 (Issue #1)





 
有的。甚至还有安卓的
 https://github.com/zqqqqz2000/intelligent-construction-android
 https://github.com/zqqqqz2000/intelligent-construction-server
